### ISSUE TITLE
Specifying priors for custom star formation histories

### ISSUE THREAD

**Issue by christopherlovell** [ACCarnall/bagpipes#3]
I'd like to be able to specify priors for each component of a custom SFH. Is this possible within the `fit_instructions` dictionary?

I thought of one hack around this, to create top hats for each component with individually specified priors. Any reason why this won't work?

Cheers!

**Comment by ACCarnall** [comment]
Hi Chris,

if you want to fit a new kind of SFH I'd recommend adding a new function to the star_formation_history class, following the model of the others. All this has to do is set the relative SFRs in each age bin (self.ages). Normalisation etc is handled by the update function.

You can then add a dictionary to fit_instructions with the same name as the new function. The function will be automatically called and passed the contents of the dictionary you added to fit_instructions. Priors will then work in the same way as they do for any other SFH component. Of course, you can easily call other SFH component types (such as multiple constants) within your new function. 

Hope that makes sense!

Cheers,
Adam

**Comment by christopherlovell** [comment]
Cheers Adam, is something like this (tidied up...) along the lines of what you're thinking?

```
def custom_8bin(self, sfr, param):

    for b in np.arange(8):
        age_max = param["b%i_max"%b]*10**9
        age_min = param["b%i_min"%b]*10**9
        frac = param["b%i_frac"%b]

        mask = (self.ages > age_min) & (self.ages < age_max)
        sfr[mask] += frac
```

I could of course write each bin explicitly. This then allows you to specify each individual prior:

```
custom = {}
custom["b1_max"] = 1
custom["b1_min"] = 0.1
custom["b1_frac_prior"] = "Gaussian"
component["b1_frac_prior_mu"] = 0.5
component["b1_frac_prior_sigma"] = 0.1
custom["b2_frac_prior"] = "Gaussian" 
# etc...
```

On a related note, how do you recommend installing from source and obtaining the grids?

**Comment by ACCarnall** [comment]
Hi Chris,

Yeah that looks good to me, two small points you might want to consider: 1.) you won't get exactly the bin edges you're specifying, due to the finite sampling in self.ages, 2.) strange things may happen when you vary the redshift, and hence the age of the Universe. Currently the default behaviour is to return no spectrum when stars in the model are older than the Universe, so you might want to make sure this doesn't happen in your function. The class already has a self.age_of_universe variable you can use.

To install from source I'd probably download the package manually from pypi: https://pypi.org/project/bagpipes

**Comment by christopherlovell** [comment]
Got you, thanks for all the help! I'll close this for now
