### ISSUE TITLE
Instructions to build custom model grid?

### ISSUE THREAD

**Issue by Jerry-Ma** [ACCarnall/bagpipes#31]
Hi,

Thanks a lot for this fantastic tool! I was wondering if we can have the ability to customize the built-in model grids?

In particular, I am looking for creating the nebular emission model with a larger range of logU than the current (-4, -2).

Any help would be highly appreciated!

**Comment by ACCarnall** [comment]
Thanks for getting in touch! This is hopefully a fairly straightforward process, try out the following instructions and let me know if you have any trouble:

 - Update bagpipes/config.py with your desired changes (e.g. new logU values, new stellar models).

 - Install cloudy.

 - Make yourself a new folder somewhere and run the following python code:

        import bagpipes as pipes
        pipes.models.making.make_cloudy_models.run_cloudy_grid()

 - Point the bagpipes/config.py file to the new nebular grids (which will by default be in cloudy_temp_files/grids within your new folder).

**Comment by Nikhil0504** [comment]
Hey,

I was going through the same issue and got it. I would like to provide the steps for it in the issue since the documentation to create new cloudy models was really spare.

If you want to change the logU values, go the `config.py` file in L112. 

First, we will need to create two new environment variables `CLOUDY_DATA_PATH` and `CLOUDY_EXE` that directs to the cloudy data folder and `cloudy.exe` files respectively.

Here is a template code in python for that (if you don't want it in your shell config):
```python
import os

os.environ['CLOUDY_DATA_PATH'] = '/Users/user/Documents/Astronomy_Research/Software/c17.03/data'
os.environ['CLOUDY_EXE'] = '/Users/user/Documents/Astronomy_Research/Software/c17.03/source/cloudy.exe'
```

After making these environment variables you can run this to create the new cloudy grids.
```python
import bagpipes as pipes
pipes.models.making.make_cloudy_models.run_cloudy_grid()
```

This should create the grids for you!

**Comment by MohammadRih** [comment]
Hi,
I plan to make a more extensive model for the range of logU. I have followed the path that was mentioned and everything seems to be going well, but it seems that I ran into a problem at the last stage. I have brought you the picture of the problem, and according to my investigations, I have found that the Bagpipes has saved and named about 124 lines in the ''cloudy_lines.txt'', but Cloudy has created only about 40 lines in the ''.lines'' file, and it seems that at this point I have a problem.
I will be very happy and grateful if you provide me a solution if you think so.
![Screenshot from 2024-03-24 11-30-15](https://github.com/ACCarnall/bagpipes/assets/104624684/3749835d-c585-4d32-b8cc-12330ec597b8)

**Comment by pietro31700** [comment]
Hi,
I've just faced this problem. In the newer versions of cloudy the line TOTL 1.08303m is no longer recognised and cloudy is stopped there when building lines (line 42).
I've solved replacing "TOTL" with "Blnd" in the file cloudy_lines.txt. The easiest way to achieve this without editing bagpipes' files is to directly change the file in the cloudy installation: "<cloudy dir>/data/pipes_cloudy_lines.txt" that you should already have because you have launched make_grids() once. When starting the creation of new grids bagpipes check if that file exists in the cloudy installation directory and in that case it won't replace it, so you can safely edit it.

**Comment by MohammadRih** [comment]
Thanks for your kind and fully described reply and solution to this problem. 
I have a small question and that is, you mentioned by replacing "TOTL" with "Blnd" the problem was solved. I cannot understand it correctly. Do You mean I should just replace "TOTL" with "Blnd" and keep the wavelength untouchable or should I have to correct the wavelength with another value too?!
thanks for your patience

**Comment by pietro31700** [comment]
Hi,
It should be fine to replace the type of blending only, however the now used line is `Blnd 1.08302m` as you can find here [Cloudy_He_lines](https://gitlab.nublado.org/cloudy/cloudy/-/blob/f1bb38314b8e48577e916ab2410dbe4b83b900b3/data/LineList_He_like.dat)

**Comment by MohammadRih** [comment]
Thanks 
I am very grateful for your help.

**Comment by ACCarnall** [comment]
Glad you found your answer, and thanks Pietro. I'll just add that the version of Cloudy that the current bagpipes version was written for is 17.03, so if you want to get things working without any changes to bagpipes I'd expect you can just install this cloudy version and carry on as normal. I'll add updating bagpipes to work with the latest cloudy version to my to-do list.

**Comment by MohammadRih** [comment]
Thanks a lot for the more detail you provide; having these updates is wonderful.

**Comment by ACCarnall** [comment]
Just to note that bagpipes is now compatible with Cloudy v25.00, rather than the earlier v17.03
