### ISSUE TITLE
MultiNest aborts when fitting

### ISSUE THREAD

**Issue by PatrickOgle** [ACCarnall/bagpipes#55]
I am having trouble getting fitting to work:

fit = pipes.fit(galaxy, fit_instructions)

yields a dead jupyter notebook kernel and the following output to the terminal:

" *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    2
 resuming from previous job
 *****************************************************
 Starting MultiNest
 ERROR: live points file has less than          400  points.
 Aborting
"

**Comment by ACCarnall** [comment]
Hi Patrick,

MultiNest saves some state files so you can re-start a fit from where it left off. These are put in the pipes/posterior directory. Unfortunately this means that when something goes wrong the corrupted state is also saved and it tries to restart from them rather than starting fresh. You need to go into the pipes/posterior folder and delete the corrupted multinest state files to get it to start fresh.

Cheers,
Adam

**Comment by PatrickOgle** [comment]
@ACCarnall That worked!  Many thanks,

Patrick
