### ISSUE TITLE
dust extincted and dust unextincted sed 

### ISSUE THREAD

**Issue by shruti-ramaiya** [ACCarnall/bagpipes#86]
Hi,

I've run bagpipes on some data and seeing it returns a final sed fit (which includes the effects of dust extinction), this is all good and I can access this final sed model through the following,

`fit.fitted_model.model_galaxy.spectrum_full`

or to plot it (either plt.plot on above, or)

`fit.fitted_model.model_galaxy.plot_full_spectrum()`

I was wondering, is it possible to extract the unextincted sed or the sed model before dust extinction is applied? for context, I wish to just recalculate the value of Av but wanting to do this myself (alongside the bagpipes returned values) and so need both model seds for this

thanks

**Comment by ACCarnall** [comment]
The best way to do this would be to write your own code to re-generate the models in the posterior, but leave out the dust attenuation component.

**Comment by shruti-ramaiya** [comment]
Thanks! will do that

**Comment by shruti-ramaiya** [comment]
Hi,

I've been attempting to do this by feeding the model components that result from my fit and feed it into the model_galaxy function and I noticed some discrepancies between parameter constraints (which im not sure should be the case), when running bagpipes on some galaxy, I get constrained values as follows e.g.

![Screenshot 2024-07-31 at 12 28 08](https://github.com/user-attachments/assets/2107311c-37e2-43a5-a401-8a4ce95eca01)

but then when going to access these constraints (so to then feed into a galaxy model), I used the code,

`fit.fitted_model.model_components`

and the results I get are as follows,

![Screenshot 2024-07-31 at 12 29 44](https://github.com/user-attachments/assets/1a3fda4a-b7d1-4fb4-864c-3e266d3ad18b)

and there are some inconsistencies with the returned values between both. Perhaps this is intentional with the code and im not accessing what I need the correct way but wanted to ask, is there then a way of getting the model components constrained by the fit as in the first screenshot?

Thank you

**Comment by ACCarnall** [comment]
I think you're perhaps not quite understanding how bagpipes fits models to data - this is done with a sampling algorithm (MultiNest in your case) that returns a bunch of different fitted models that are equally weighted samples from the posterior distribution. It doesn't find the "best fit" as such, and the two objects fit.model_galaxy and fit.posterior.model_galaxy are just convenient places for the code to store whatever model it's been working with most recently. The samples from the posterior are contained in the fit.posterior.samples dictionary - it's the percentiles of the distributions stored here for each fitted parameter that are shown by the code when a fit finishes running.

The closest analogous thing to a "best fit" produced by the code is the posterior median. You can get the posterior median for e.g. the full spectrum by doing np.median(fit.posterior.samples["spectrum_full"], axis=0). fit.posterior.model_galaxy.wavelengths is just a convenient place to go to get the associated wavelengths for each spectrum point, since these don't change between samples.

If you want to re-generate the posterior distribution (i.e. all the fitted models in the posterior) without dust you'll need to do something a bit more sophisticated, e.g.,

```
import numpy as np
import bagpipes as pipes
from copy import deepcopy

desired_wavs = np.arange(5000, 10000, 10)
spec_posterior_nodust = np.zeros((fit.n_posterior, desired_wavs.shape[0]))

for i in range(fit.n_posterior):
    params = fit.results["samples2d"][i, :]
    fit.fitted_model._update_model_components(params)
    desired_model_comp = deepcopy(fit.fitted_model.model_components)
    del desired_model_comp["dust"]
    pipes.model_galaxy(desired_model_comp, spec_wavs=desired_wavs)
    spec_posterior_nodust[i, :] = model_galaxy.spectrum[:, 1]
    
post_med_spec_nodust = np.c_[desired_wavs, np.median(spec_posterior_nodust, axis=0)]

```

**Comment by shruti-ramaiya** [comment]
Hi Adam,

Thanks for getting back to me on this and explaining. I realised through looking at the source code that fit.posterior was sampling randomly from the posterior, hence the output model would change every time but I couldn't quite figure out what the numbers returned by fit.fitted_model were returning since they were different to the printed percentiles - so thanks for clarifying this. Also in regards to the dust model, my thinking wasn't more a 'best fit' model but for just a single output model, to keep all returned parameters fixed except dust (as opposed to resampling from posterior where the other parameters may vary slightly) hence the reason for generating a galaxy model with my defined inputs but I appreciate you highlighting what you meant  in more detail.

Thanks again
