### ISSUE TITLE
Iyer (2019) non-parametric SFH prior

### ISSUE THREAD

**Issue by AinaSo** [ACCarnall/bagpipes#91]
Hi.
I'm trying to use iyer sfh but I have issues to do this.
I have put the prior distribution as follows:

```
iyer = {}                          
iyer["sfr"] = (1 ,10)            
iyer["bins"] = 5            
iyer["bins_prior"] = "dirichlet" 
iyer["alpha"] = 1
iyer["massformed"] =  (1., 15.)  
iyer["metallicity"] = (0., 2.5)     

fit_instructions = {} 
fit_instructions["redshift"] = 0 
fit_instructions["iyer"] = iyer
```
The fitting process is completed, but it does not provide us with any useful output. 

Is the prior distribution placed wrong?

Thank you.

**Comment by ACCarnall** [comment]
Hi there,

I believe the issue here is probably specifying redshift = 0. This causes the output models to be generated in different units, which probably are not compatible with your data. See this section of the documentation: https://bagpipes.readthedocs.io/en/latest/model_galaxies.html#note-on-units-at-redshift-zero

Cheers,
Adam

**Comment by AinaSo** [comment]
Thank you for your swift response.
Then I put fit_instructions["redshift"] = 2, but it didn't work well...

The error message is as follows (excerpt):
```
packages/bagpipes/models/star_formation_history.py:125): RuntimeWarning: divide by zero encountered in log10
  self.stellar_mass = np.log10(np.sum(self.live_frac_grid*self.ceh.grid))
packages/bagpipes/models/star_formation_history.py:126): RuntimeWarning: divide by zero encountered in log10
  self.formed_mass = np.log10(np.sum(self.ceh.grid))

ValueError: zero-size array to reduction operation minimum which has no identity
```

Posterior percentiles are shown.
However, a figure is not plotted.

**Comment by AinaSo** [comment]
This is the same error as redshift zero.
The version of bagpipes is 1.1.1. But what is dense_basis?
That's the first I've heard of it.
Is this (https://dense-basis.readthedocs.io/en/latest/usage/installation.html)?
Is this necessary?　

Now, it works well with parametric SFH models.
I get the above error when I change the SFH model to Iyer (2019).

**Comment by ACCarnall** [comment]
Yes, this SFH model requires Kartheik Iyer's dense basis code. Hopefully this is the issue, though I'd have expected to see a more informative error message. I'd also recommend updating to bagpipes 1.2.0.

**Comment by AinaSo** [comment]
I got it. Thank you very much.

Though I installed “dense_basis”,  I’m unsure where I should change to use the iyer non-parametric model in the code with bagpipes…

**Comment by ACCarnall** [comment]
You shouldn't need to change anything, bagpipes should load up dense_basis and use it automatically, as long as import dense_basis works for you in a python terminal.

**Comment by ErikOsinga** [comment]
Hi, 

I found this issue because I was running into the same error message with a different `fit_instructions` dictionary:

```
packages/bagpipes/models/star_formation_history.py:125): RuntimeWarning: divide by zero encountered in log10
  self.stellar_mass = np.log10(np.sum(self.live_frac_grid*self.ceh.grid))
packages/bagpipes/models/star_formation_history.py:126): RuntimeWarning: divide by zero encountered in log10
  self.formed_mass = np.log10(np.sum(self.ceh.grid))

ValueError: zero-size array to reduction operation minimum which has no identity
```

I believe the problem happens when specifying a component that is not named in one of the "`star_formation_history`" attributes. In my case, I was trying

```
    # Star Formation History component - Double Power Law
    sfh = {
        "type": "double_power_law",
        "alpha": (0.01, 100.),           # Slope of the falling SFR
        "beta": (0.01, 100.),            # Slope of the rising SFR
        "tau": (0.01, age_universe),     # Time at which SFR peaks, between 0.01 Gyr and the age of the Universe
        "massformed": (6., 13.),         # Logarithm of total mass formed (log10(M*/M_sun))
        "age": (0.01, age_universe)      # Age of the galaxy, from 0.01 Gyr to the age of the Universe
    }
    fit_instructions = {  "double_power_law": sfh }
```
Which should have been
`fit_instructions = {  "dblplaw": sfh }`
_(I think, the caveat is that I just started using bagpipes yesterday, so this might be wrong, as it raises a different error but does seem to be actually fitting now.)_

In the case of @AinaSo , I think `fit_instructions["iyer"] = iyer` should be `fit_instructions["iyer2019"] = iyer`, as also mentioned in #73. 

The code doesn't raise an error if the user inputs a `fit_instructions` star-formation history component that doesn't exist, but will "complete" the fitting, and print the parameter percentiles. which are simply the priors, in my case:

```
Completed in 50.2 seconds.

Parameter                          Posterior percentiles
                                16th       50th       84th
----------------------------------------------------------
double_power_law:age           2.406      7.481     12.579
double_power_law:alpha        15.994     50.022     84.194
double_power_law:beta         16.179     49.816     84.115
double_power_law:tau           2.428      7.480     12.589
```

It might be nice to implement a check for star-formation components. Because of these lines it will fail silently and give this weird error:

```
        # Detect SFH components
        comp_list = list(model_components)
        self.components = ([k for k in comp_list if k in dir(self)]
                           + [k for k in comp_list if k[:-1] in dir(self)])

```

**Comment by AinaSo** [comment]
Thank you very much.
It works!

**Comment by ACCarnall** [comment]
Ah, thanks very much Erik, yes this makes sense of what was going on. I'll make myself a note to update the documentation and put a check in the code to at least throw a warning in this circumstance.

**Comment by AinaSo** [comment]
By the way, what are the units for iyer[‘sfr’]=mandatory, as in previous questions?
log(M_sun/yr) or just M_sun/yr?

**Comment by ACCarnall** [comment]
The units are just Solar masses per year. For more detailed questions about dense basis I'd recommend taking a look at the documentation for that code, or contacting its developer.
