### ISSUE TITLE
Questions about ionization parameter and expected flux

### ISSUE THREAD

**Issue by Gamiro00** [ACCarnall/bagpipes#95]
Hi, I am currently trying to derive the stellar mass of a galaxy at z=1.99, and I would like my ionization parameter to range between (-4 and -1). However, I have the old version of bagpipes. I also saw this #31, I wonder if I only want  to update the limits of logU. Is it enough to update the L112 in the config.py file, or must I create new cloudy models?

I also wonder if there is a specific reason why the expected flux(orange points) on the SED do not appear? I attached an image of my SED of this galaxy and as you can see at wavelength log(wave/Å) = 3.52, the orange point is not shown.

Thank you in advance!

![Screenshot from 2024-11-20 14-22-59](https://github.com/user-attachments/assets/6fc39eb6-2005-4c0f-ab01-963416fdb5b6)

**Comment by ACCarnall** [comment]
You'd need to run new cloudy models yes, just updating config.py does not create new models. However the most recent version of bagpipes does have that full range covered from -1 to -4, so I'd recommend just upgrading to the latest version.

The orange prediction for that band is not shown because it is higher than the top of the plot.

**Comment by Gamiro00** [comment]
Thank you very much for your reply. I used matplotlib widget to see if there was this prediction point but I couldn't find it. It was therefore I thought that it could be something else. But thank you again!
Best, 
Gabriela

**Comment by ACCarnall** [comment]
Ah yes, I'd forgotten but there's a bit of code in bagpipes that checks for predictions off the top of the plot and doesn't plot anything if (the raster plotting function crashes in this scenario). If you change the axis limits so that the predictions are within the shown range then the points should appear.
